server:
    port: 7799
    servlet:
        context-path: /zoo

# zookeeper
zookeeper:
    address: 22.144.101.47:2181,22.144.101.47:2182,22.144.101.47:2183
    sessionTimeout: 50000
    connectionTimeout: 40000

spring:
    datasource:
        driver-class-name:


custom:
    myself:
        age: 15
        like: like
        name: name

start:
    student:
        name: liuweian